# ci.yml file for GitHub Actions
# https://github.com/TypeStrong/typedoc/issues/1485
name: CI Build step

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "18.x"

      - name: Install
        run: yarn install

      - name: Test to see if the project compiles
        run: yarn build
